version: '3.8'
services:
  be:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - release_version=docker-compose
    image: mildblue/covid-vaxx
    env_file: .env
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: postgres:13
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - covid-vaxx-db:/var/lib/postgresql/data/

volumes:
  covid-vaxx-db:
